### ISSUE TITLE
Backstage container init error

### ISSUE THREAD

**Issue by kubealex** [janus-idp/helm-backstage#170]
### Describe the bug

When installing via chart, the backstage container fails its init phase:

runc create failed: unable to start container process: exec: \"./install-dynamic-plugins.sh\": stat ./install-dynamic-plugins.sh: no such file or directory"

### Expected Behavior

The container starts.

### What are the steps to reproduce this bug?

1. Follow instructions in the README
2. Add helm repos
3. (optional) customize values
4. Helm install

### Versions of software used and environment

OCP 4.14 fresh install with ODF
OCP 4.13 fresh install with ODF

**Comment by Zaperex** [comment]
This bug is currently due to [`quay.io/janus-idp/backstage-showcase:latest`](https://quay.io/janus-idp/backstage-showcase:latest) still pointing to an image from before dynamic plugins were added (hence the missing `./install-dynamic-plugins.sh` file).

A workaround at the moment is to change the `upstream.backstage.image.tag` to `next` or any of newer images in [`quay.io/janus-idp/backstage-showcase`](https://quay.io/repository/janus-idp/backstage-showcase?tab=tags)

**Comment by kubealex** [comment]
Thank you @Zaperex!

**Comment by kadel** [comment]
this is fixed now [quay.io/janus-idp/backstage-showcase:latest](https://quay.io/janus-idp/backstage-showcase:latest) now points to the latest released version (1.0.0) which includes dynamic plugins
