### ISSUE TITLE
fix README file by providing correct instruction

### ISSUE THREAD

**Issue by josephca** [janus-idp/helm-backstage#74]
Minor bugs need to be fixed in [readme](https://github.com/janus-idp/helm-backstage/blob/main/README.md),

- `helm upgrade -i oci://ghcr.io/janus-idp/helm-backstage/backstage --version=<version>` 
should be  updated to 
`helm upgrade -i <release-name> oci://ghcr.io/janus-idp/helm-backstage/backstage --version=<version>`
- when installing from oci repository, a user needs to set `HELM_EXPERIMENTAL_OCI=1` to avoid installation errors. It would be nicer to have the instruction in README. 
However,  the error message contains the correct instruction to fix the error :  
```
Installing janus backstage on OpenShift
Error: this feature has been marked as experimental and is not enabled by default. Please set HELM_EXPERIMENTAL_OCI=1 in your environment to use this feature
```

**Comment by tumido** [comment]
Hi @josephca, thanks for raising this issue.

1. Yes, the release name should be updated in the README, I'll update it. Thank you! 🙂 
2. The `HELM_EXPERIMANTAL_OCI` flag is deprecated since Helm `v3.8.0` which was released in January of 2022. That is a year and a half ago. (See: https://helm.sh/docs/topics/registries/, https://github.com/helm/helm/releases/tag/v3.8.0). I don't think we should advise users on this since we don't aim to support every Helm version, so this should be safe to omit from the README.

**Comment by josephca** [comment]
@tumido I found one more place which may require a fix. 
From https://github.com/janus-idp/helm-backstage/blob/main/charts/backstage/README.md, at the end of the readme

_upstream:
   `backstage:`. -> it's missing
          appConfig:
              app:_

**Comment by tumido** [comment]
I've updated the PR. Thank you for noticing 👍 🙂
