### ISSUE TITLE
Question: Why another helm chart project ?

### ISSUE THREAD

**Issue by cmoulliard** [janus-idp/helm-backstage#9]
## Question 

As a backstage initiative project already exists, I'm wondering why you created another helm chart project ?

https://github.com/vinzscam/backstage-chart
https://github.com/backstage/backstage/issues/4945

Remark: That would be great to unify the 2 existing helm charts !

**Comment by froblesmartin** [comment]
@sabre1041 @vinzscam could you sync? :)

**Comment by cmoulliard** [comment]
See response of Chris Burns - https://github.com/backstage/backstage/issues/4945#issuecomment-1290292133

**Comment by sabre1041** [comment]
@cmoulliard @froblesmartin This chart exists as there is no existing centralized Helm chart for deploying backstage. There have been some discussions as in https://github.com/backstage/backstage/issues/4945 on a centralized location. 

I'd be happy to collaborate with the community on providing a unified helm chart that takes the best of all implementations thus far

**Comment by ozialien** [comment]
It might be a wider scope.  Admittedly the more people use a common chart the more switching can be unified.   

Recently our generic kubernetes chart (homegrown) was updated to support openshift.  Which resulted in a interim refactor of:

-f resource-dev/prod/?.yaml -f default-app-config.yaml -f openshift-values.yaml -f values.yml

where openshift-values.yaml had a lot of securityContext switching vs vanilla.

**Comment by ChrisJBurns** [comment]
Currently awaiting Discord phone timeouts before I get back into my account. I shall be on the relevant channels soon :+1:

**Comment by riginoommen** [comment]
I see another helmchart recently opensourced for backstage - https://github.com/backstage/charts

**Comment by wadebee** [comment]
If the new home is going to be https://github.com/backstage/charts shouldn't this repo be deprecated as well?

**Comment by tumido** [comment]
Thank you for this discussion! As you can see, situation changed over time and from the time of "there's no proper Helm chart around that is robust enough" (aka the time when this repo was created) we got to a point when we have a solid and stable upstream helm chart at https://github.com/backstage/charts 

The upstream chart is very versatile, maintained and overall in a good shape. However due to it's nature of a truly upstream chart, it does not feature platform specific integrations we strive for in Janus. Therefore we should repurpose this chart and make it so it:

1. Respects and uses the upstream chart.
2. Provide OpenShift specific capabilities like support for [`Route`s](https://github.com/janus-idp/helm-backstage/blob/main/charts/backstage/templates/route.yaml) and [S2I builds via `BuildConfig`](https://github.com/janus-idp/helm-backstage/pull/7), etc.

I propose following plan:

1. Remove the current chart from the repo
2. Create a new one that would list the upstream chart as a [Helm dependency](https://helm.sh/docs/helm/helm_dependency/). (If we choose the new chart to use the same name as the current one, we introduce this as a **breaking change** by changing the MAJOR semver).
3. Provides sane default values for deployment on OpenShift
4. Extends the chart with capabilities mentioned above

Please let me know what you think.

**Comment by sabre1041** [comment]
@tumido agree with you that the upstream chart has matured nicely since the impetus of the chart effort in the Janus project. I also (strongly) agree that we should extend through a dependency mechanism and not fork the upstream chart.

+1 to all the above

**Comment by schultzp2020** [comment]
@tumido this approach looks good to me.
